name: kraken-api
namespace: kraken
replicaCount: 1

s3:
  bucketName: kraken-plugins
  endpoint: minio-kraken.duckdns.org

db:
  host: "kraken-db.kraken.svc.cluster.local"

api:
  rabbitmqBaseUrl: "rabbitmq.rabbitmq.svc.cluster.local:5672"
  baseUrl: "https://kraken-api.duckdns.org"

redis:
  name: redis

  image:
    repository: redis
    tag: "8.0.3-alpine"
    pullPolicy: IfNotPresent

  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "512Mi"
      cpu: "500m"

  persistence:
    name: redis-pvc
    enabled: true
    storageClass: "longhorn"
    size: 8Gi

  config:
    maxmemory: "256mb"
    maxmemory_policy: "allkeys-lru"
    timeout: 300
    tcp_keepalive: 60

  service:
    type: ClusterIP
    port: 6379
    name: redis-svc

  metrics:
    enabled: true
    image:
      repository: oliver006/redis_exporter
      tag: "v1.45.0"
    port: 9121

image:
  repository: cbartram/kraken-api
  pullPolicy: IfNotPresent
  tag: "0.0.73" # 0.0.73

serviceAccountName: kraken-api-sa

service:
  frontendServiceName: kraken-frontend-service
  type: ClusterIP
  port: 80
  targetPort: 8080

resources:
   limits:
     cpu: 200m
     memory: 256Mi
   requests:
     cpu: 100m
     memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
