name: kraken-api
frontendServiceName: kraken-frontend-service
namespace: kraken
replicaCount: 1

s3:
  bucketName: kraken-plugins

db:
  host: "kraken-db.kraken.svc.cluster.local"

api:
  rabbitmqBaseUrl: "rabbitmq.rabbitmq.svc.cluster.local:5672"
  baseUrl: "https://kraken-api.duckdns.org"

image:
  repository: cbartram/kraken-api
  pullPolicy: IfNotPresent
  tag: "0.0.41"

serviceAccountName: kraken-api-sa

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

resources:
   limits:
     cpu: 100m
     memory: 128Mi
   requests:
     cpu: 100m
     memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
