package com.kraken.api.input.mouse;

import com.google.inject.Singleton;
import com.kraken.api.service.util.RandomService;
import lombok.Getter;
import lombok.Setter;
import lombok.extern.slf4j.Slf4j;
import net.runelite.api.Client;
import net.runelite.api.Point;

import javax.inject.Inject;
import java.awt.*;
import java.awt.event.MouseEvent;
import java.awt.event.MouseWheelEvent;
import java.util.concurrent.Executors;
import java.util.concurrent.ScheduledExecutorService;
import java.util.concurrent.TimeUnit;

@Slf4j
@Singleton
public class VirtualMouse {

    private final Client client;
    private final ScheduledExecutorService scheduledExecutorService;

    @Getter
    private final Canvas canvas;

    @Getter
    @Setter
    private Point lastMove = new Point(-1, -1);

    @Inject
    public VirtualMouse(Client client) {
        this.scheduledExecutorService = Executors.newScheduledThreadPool(10);
        this.client = client;
        this.canvas = client.getCanvas();
    }

    /**
     * Moves the mouse to the specified point.
     *
     * @param point The destination point.
     * @return The VirtualMouse instance for chaining.
     */
    public VirtualMouse move(Point point) {
        setLastMove(point);
        MouseEvent mouseMove = new MouseEvent(getCanvas(), MouseEvent.MOUSE_MOVED, System.currentTimeMillis(), 0, point.getX(), point.getY(), 0, false);
        mouseMove.setSource("Kraken");
        getCanvas().dispatchEvent(mouseMove);

        return this;
    }

    /**
     * Moves the mouse to the center of the specified rectangle.
     *
     * @param rect The rectangle to move to.
     * @return The VirtualMouse instance for chaining.
     */
    public VirtualMouse move(Rectangle rect) {
        MouseEvent mouseMove = new MouseEvent(client.getCanvas(), MouseEvent.MOUSE_MOVED, System.currentTimeMillis(), 0, (int) rect.getCenterX(), (int) rect.getCenterY(), 0, false);
        mouseMove.setSource("Kraken");
        getCanvas().dispatchEvent(mouseMove);

        return this;
    }

    /**
     * Moves the mouse to the center of the specified polygon.
     *
     * @param polygon The polygon to move to.
     * @return The VirtualMouse instance for chaining.
     */
    public VirtualMouse move(Polygon polygon) {
        Point point = new Point((int) polygon.getBounds().getCenterX(), (int) polygon.getBounds().getCenterY());

        MouseEvent mouseMove = new MouseEvent(getCanvas(), MouseEvent.MOUSE_MOVED, System.currentTimeMillis(), 0, point.getX(), point.getY(), 0, false);
        mouseMove.setSource("Kraken");
        getCanvas().dispatchEvent(mouseMove);

        return this;
    }

    /**
     * Scrolls the mouse wheel down at the specified point.
     *
     * @param point The point where the scroll occurs.
     * @return The VirtualMouse instance for chaining.
     */
    public VirtualMouse scrollDown(Point point) {
        long time = System.currentTimeMillis();

        move(point);

        scheduledExecutorService.schedule(() -> {
            MouseEvent mouseScroll = new MouseWheelEvent(getCanvas(), MouseEvent.MOUSE_WHEEL, time, 0, point.getX(), point.getY(), 0, false,
                    MouseWheelEvent.WHEEL_UNIT_SCROLL, 10, 2);
            mouseScroll.setSource("Kraken");
            getCanvas().dispatchEvent(mouseScroll);
        }, RandomService.between(40,100), TimeUnit.MILLISECONDS);
        return this;
    }

    /**
     * Scrolls the mouse wheel up at the specified point.
     *
     * @param point The point where the scroll occurs.
     * @return The VirtualMouse instance for chaining.
     */
    public VirtualMouse scrollUp(Point point) {
        long time = System.currentTimeMillis();

        move(point);

        scheduledExecutorService.schedule(() -> {
            MouseEvent mouseScroll = new MouseWheelEvent(getCanvas(), MouseEvent.MOUSE_WHEEL, time, 0, point.getX(), point.getY(), 0, false,
                    MouseWheelEvent.WHEEL_UNIT_SCROLL, -10, -2);
            mouseScroll.setSource("Kraken");
            getCanvas().dispatchEvent(mouseScroll);
        }, RandomService.between(40,100), TimeUnit.MILLISECONDS);
        return this;
    }

    /**
     * Gets the last known mouse position from a move event generated by this class.
     *
     * @return The last move point.
     */
    public java.awt.Point getMousePosition() {
        Point point = lastMove;
        return new java.awt.Point(point.getX(), point.getY());
    }

    /**
     * Gets the current mouse position from the AWT Canvas component.
     *
     * @return The system mouse position relative to the canvas.
     */
    public java.awt.Point getCanvasMousePosition() {
       return client.getCanvas().getMousePosition();
    }

    /**
     * Moves the mouse to the specified coordinates.
     *
     * @param x The x coordinate.
     * @param y The y coordinate.
     * @return The VirtualMouse instance for chaining.
     */
    public VirtualMouse move(int x, int y) {
        return move(new Point(x, y));
    }


    /**
     * Moves the mouse to the specified coordinates.
     *
     * @param x The x coordinate.
     * @param y The y coordinate.
     * @return The VirtualMouse instance for chaining.
     */
    public VirtualMouse move(double x, double y) {
        return move(new Point((int) x, (int) y));
    }

    private synchronized void pressed(Point point, int button) {
        MouseEvent event = new MouseEvent(client.getCanvas(), MouseEvent.MOUSE_PRESSED, System.currentTimeMillis(), 0, point.getX(), point.getY(), 1, false, button);
        event.setSource("Kraken");
        getCanvas().dispatchEvent(event);
    }

    private synchronized void released(Point point, int button) {
        MouseEvent event = new MouseEvent(client.getCanvas(), MouseEvent.MOUSE_RELEASED, System.currentTimeMillis(), 0, point.getX(), point.getY(), 1, false, button);
        event.setSource("Kraken");
        getCanvas().dispatchEvent(event);
    }

    private synchronized void clicked(Point point, int button) {
        MouseEvent event = new MouseEvent(client.getCanvas(), MouseEvent.MOUSE_CLICKED, System.currentTimeMillis(), 0, point.getX(), point.getY(), 1, false, button);
        event.setSource("Kraken");
        getCanvas().dispatchEvent(event);
    }

    private synchronized void exited(Point point) {
        MouseEvent event = new MouseEvent(client.getCanvas(), MouseEvent.MOUSE_EXITED, System.currentTimeMillis(), 0, point.getX(), point.getY(), 0, false);
        event.setSource("Kraken");
        getCanvas().dispatchEvent(event);
    }

    private synchronized void entered(Point point) {
        MouseEvent event = new MouseEvent(client.getCanvas(), MouseEvent.MOUSE_ENTERED, System.currentTimeMillis(), 0, point.getX(), point.getY(), 0, false);
        event.setSource("Kraken");
        getCanvas().dispatchEvent(event);
    }

    private synchronized void moved(Point point) {
        MouseEvent event = new MouseEvent(client.getCanvas(), MouseEvent.MOUSE_MOVED, System.currentTimeMillis(), 0, point.getX(), point.getY(), 0, false);
        event.setSource("Kraken");
        getCanvas().dispatchEvent(event);
    }
}


