package com.kraken.api.core.packet.entity;

import com.google.inject.Inject;
import com.google.inject.Provider;
import com.google.inject.Singleton;
import com.kraken.api.core.packet.PacketClient;
import com.kraken.api.core.packet.model.PacketDefFactory;
import net.runelite.api.Client;

@Singleton
public class SailingPackets {

    @Inject
    private Client client;

    @Inject
    private Provider<PacketClient> packetSenderProvider;

    @Inject
    private PacketDefFactory packetDefFactory;


    /**
     * Queues a packet to set the direction of the boat in the game.
     * This method constructs and sends a packet to update the heading/direction based
     * on the specified direction parameter. Direction parameters range from 0 = south to 15 = south_south_east
     * <p></p>
     * The full mapping can be seen here:
     *  SOUTH(0),
     *  SOUTH_SOUTH_WEST(1),
     *  SOUTH_WEST(2),
     *  WEST_SOUTH_WEST(3),
     *  WEST(4),
     *  WEST_NORTH_WEST(5),
     *  NORTH_WEST(6),
     *  NORTH_NORTH_WEST(7),
     *  NORTH(8),
     *  NORTH_NORTH_EAST(9),
     *  NORTH_EAST(10),
     *  EAST_NORTH_EAST(11),
     *  EAST(12),
     *  EAST_SOUTH_EAST(13),
     *  SOUTH_EAST(14),
     *  SOUTH_SOUTH_EAST(15);
     *
     * <p>The packet is built using the {@literal @}link PacketDefinition generated by
     * the {@literal @}code getSetHeading() method, and the direction value is included
     * in the packet payload.</p>
     *
     * @param direction The new direction to set, typically represented as an integer.
     *                  The exact value may depend on how directions are defined in the game
     *                  (e.g., 0 for North, 1 for East, etc.).
     */
    public void queueSetDirection(int direction) {
        if(direction < 0 || direction > 15) {
            throw new IllegalArgumentException("Invalid direction value: " + direction + ", expected 0-15");
        }
        packetSenderProvider.get().sendPacket(packetDefFactory.getSetHeading(), direction);
    }
}
