apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.redis.service.name }}
spec:
  type: {{ .Values.redis.service.type }}
  ports:
    - port: {{ .Values.redis.service.port }}
      targetPort: {{.Values.redis.service.port}}
      protocol: TCP
      name: {{.Values.redis.name}}
    {{- if .Values.redis.metrics.enabled }}
    - port: {{ .Values.redis.metrics.port }}
      targetPort: {{ .Values.redis.metrics.port }}
      protocol: TCP
      name: metrics
    {{- end }}
  selector:
    app: {{ .Values.redis.name }}