apiVersion: v1
kind: ConfigMap
metadata:
  name: server-config
  namespace: {{.Values.namespace}}
data:
  # Versions and images for containers the API is responsible
  # for deploying
  API_VERSION: {{ .Values.image.tag | quote }}
  BUCKET_NAME: {{ .Values.s3.bucketName | quote }}
  MINIO_ENDPOINT: {{ .Values.s3.endpoint | quote }}
  GIN_MODE: "release"
  # Enables json based logs in prod with trace ids
  LOG_LEVEL: "ERROR"
  RABBITMQ_BASE_URL: {{ .Values.api.rabbitmqBaseUrl | quote }}
  API_BASE_URL: {{ .Values.api.baseUrl | quote }}
  MYSQL_HOST: {{ .Values.db.host | quote }}