apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.name}}
  namespace: {{.Values.namespace}}
  labels:
    app: {{.Values.name}}
    redis-client: "allowed"
spec:
  revisionHistoryLimit: 1
  strategy:
    type: RollingUpdate
  replicas: {{.Values.replicaCount}}
  selector:
    matchLabels:
      app: {{.Values.name}}
  template:
    metadata:
      labels:
        app: {{.Values.name}}
        redis-client: "allowed"
    spec:
      serviceAccountName: {{.Values.serviceAccountName}}
      containers:
        - name: main
          image: {{.Values.image.repository}}:{{.Values.image.tag}}
          imagePullPolicy: IfNotPresent
          args:
            - "./main"
            - "-port"
            - {{.Values.service.targetPort | quote }}
          envFrom:
            - secretRef:
                name: minio-secrets
            - secretRef:
                name: cognito-secrets
            - secretRef:
                name: discord-secrets
            - secretRef:
                name: mysql-secrets
            - secretRef:
                name: aws-secrets
            # Uncomment below to test stripe with test secrets and not charge real cards
            #- secretRef:
            #    name: stripe-secrets-test
            - secretRef:
                name: stripe-secrets
            - secretRef:
                name: gmail-secrets
            - secretRef:
                name: rabittmq-secrets
            - configMapRef:
                name: server-config
          ports:
            - containerPort: {{.Values.service.targetPort}}
              name: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /api/v1/health
              port: {{.Values.service.targetPort}}
          readinessProbe:
            httpGet:
              path: /api/v1/health
              port: {{.Values.service.targetPort}}