apiVersion: v1
kind: Service
metadata:
  name: minio-api-proxy
  namespace: {{.Values.namespace}}
spec:
  type: ExternalName
  externalName: minio-svc.minio.svc.cluster.local
  ports:
    - name: api
      port: 9000
      targetPort: 9000
---
apiVersion: v1
kind: Service
metadata:
  name: minio-console-proxy
  namespace: {{.Values.namespace}}
spec:
  type: ExternalName
  externalName: minio-svc.minio.svc.cluster.local
  ports:
    - name: console
      port: 9090
      targetPort: 9090
---
apiVersion: v1
kind: Service
metadata:
  name: argocd-server-proxy
  namespace: {{.Values.namespace}}
spec:
  type: ExternalName
  externalName: argocd-server.argocd.svc.cluster.local
  ports:
    - name: https
      port: 80
      targetPort: 80