apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespace }}
  name: {{.Values.name}}
spec:
  type: {{.Values.service.type}}
  selector:
    app: {{.Values.name}}
  ports:
    - port: {{.Values.service.port}}
      targetPort: {{.Values.service.targetPort}}
      protocol: TCP
      name: http
---
apiVersion: v1
kind: Service
metadata:
  name: argocd-server-proxy
  namespace: {{.Values.namespace}}
spec:
  type: ExternalName
  externalName: argocd-server.argocd.svc.cluster.local
  ports:
    - name: https
      port: 80
      targetPort: 80
